### PR TITLE
Russian Translation added

### PR DESCRIPTION
**Pull request by PollyGlot**
Created a new rus folder with strings.xml that contains a Russian translation for the app

### CODE REVIEW

**Comment by metalnakls** [comment]
CYKA BLYAT
Я же хотел

**Comment by PollyGlot** [comment]
@metalnakls  "Please, keep calm and take a rest"

I didn't get about what you mean saying "Вибрация". Actually speaking this word is used in the Russian localization of Android, so there is no mistake saying the same in the app.

screenshot

**Comment by franciscofranco** [comment]
Let me know when I can merge this :)

**Comment by PollyGlot** [comment]
Yes, you can. If I find any issues after the app is updated with the Russian language I will solve them and pull a request :)

**Pull request merged**
